# Generated by Django 5.2 on 2026-06-28 20:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tutores_incognito',
            field=models.BooleanField(default=False, help_text='Ocultar nombres de tutores en la revisión'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='facultad',
            field=models.CharField(choices=[('Salud', 'Ciencias de la Salud'), ('Ingenieria', 'Ingeniería'), ('Juridicas', 'Ciencias Jurídicas y Políticas'), ('Economicas', 'Ciencias Económicas y Sociales'), ('Educacion', 'Ciencias de la Educación'), ('Odontologia', 'Odontología'), ('Tecnologia', 'Ciencias y Tecnología'), ('Otra', 'Otra')], default='Otra', max_length=50),
        ),
        migrations.AlterField(
            model_name='correccion',
            name='comentario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correccion', to='gestion.comentario'),
        ),
        migrations.AlterField(
            model_name='correccion',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 28, 20, 57, 58, 199940, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('En Progreso', 'En Progreso'), ('Observado', 'Observado'), ('Aprobado', 'Aprobado'), ('PROYECTO_APROBADO', 'Finalizado Satisfactoriamente'), ('Cancelado', 'Cancelado')], default='En Progreso', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('Tesis', 'Tesis de Grado'), ('Articulo', 'Artículo Científico'), ('Proyecto', 'Proyecto de Investigación'), ('Monografia', 'Monografía')], default='Tesis', max_length=50),
        ),
    ]
