# Generated by Django 5.2 on 2026-08-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_proyecto_cancelado_por_proyecto_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisia',
            name='porcentaje_similitud',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analisisia',
            name='riesgo_texto_ia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
